# Generated by Django 4.1.7 on 2023-03-29 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option1',
            new_name='op1',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option2',
            new_name='op2',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option3',
            new_name='op3',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option4',
            new_name='op4',
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('playerName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard', to=settings.AUTH_USER_MODEL)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard', to='quiz.score')),
            ],
        ),
    ]
