# Generated by Django 4.1.7 on 2023-03-30 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_user_alter_score_playername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='playerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='playerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
