# Generated by Django 4.1.7 on 2023-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_score_playername_alter_scoreboard_playername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=3),
        ),
    ]
